[package]
name = "rusteroids"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]

[dependencies]
ggez = { version = "0.4.0", features = ["cargo-resource-root"] }
tokio = "0.1.3"
futures = "0.1.18"
actix = "0.5.3"
cgmath = "0.16.0"
rand = "0.4.2"
